config/routes.rb
Rails.application.routes.draw do
  root 'illustrations#index'

  resources :illustrations, only: %i[index show] do
    resources :titles, only: %i[create], shallow: true
  end
  resources :votes, only: %i[create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/illustration.rb
class Illustration < ApplicationRecord
  has_many :titles, dependent: :destroy

  validates :content, presence: true
end

app/models/title.rb
class Title < ApplicationRecord
  belongs_to :illustration
  has_many :votes

  validates :content, presence: true
  validates :user_name, presence: true

  def vote
    if self.vote_quantity.nil?
      self.vote_quantity = 1
    else
      self.vote_quantity += 1
    end
    self.save
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/illustrations_controller.rb
class IllustrationsController < ApplicationController
  def index
    @illustrations = Illustration.all
  end

  def show
    @illustration = Illustration.find(params[:id])
    @title = Title.new
    if params[:type] == 'order_popular'
      @titles = @illustration.titles.order(vote_quantity: :desc)
    else
      @titles = @illustration.titles.order(created_at: :desc)
    end
  end
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  def create
    @illustration = Illustration.find(params[:illustration_id])
    @title = @illustration.titles.build(title_params)
    @title.save
  end

  private

  def title_params
    params.require(:title).permit(:content, :user_name, :vote_quantity).merge(illustration_id: params[:illustration_id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @title = Title.find(params[:title_id])
    @title.vote
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/illustrations/_illustration.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div class="card">
    <div class="card-body">
      <%= link_to illustration_path(illustration) do %>
        <%= image_tag illustration.content, class: 'card-img-top', size: '200x200' %>
      <% end %>
    </div>
  </div>
</div>

app/views/illustrations/index.html.erb
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1>いらすとやタイトル選手権</h1>
      <p>　欲しい素材が必ず見つかるサイト"いらすとや"</p>
      <p>　中にはぱっと見てよくわからない素材も...</p>
      <p>　あなたならどんなタイトルをつけますか？？</p>
      <p>　「ありやな〜」と思ったタイトルは<%= image_tag 'text_yu.png', size: '25x25' %>ボタンで応援してね（連打歓迎）</p>
      <!-- いらすと一覧 -->
      <div class="row">
        <div class="col-12">
          <div class="row">
            <% if @illustrations.present? %>
              <%= render @illustrations %>
            <% else %>
              <p><%= t('.no_result') %></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/illustrations/show.html.erb
<div class="container pt-3">
  <div class="col-lg-8 offset-lg-2">
    <div class="card mb-3">
      <div class="row no-gutters">
        <div class="col-lg-4 text-center">
          <h3><%= t('.illustration') %></h3>
          <%= image_tag @illustration.content, class: 'img-fluid', size: '200x200' %>
        </div>
        <div class="col-lg-8">
          <div class="card-body">
            <!-- 投稿フォーム -->
            <%= render 'titles/form', { illustration: @illustration, title: @title } %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <p>
    <button class="col-lg-8 offset-lg-2 btn btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-titles" aria-expanded="false" aria-controls="collapse-titles">
      みんなの投稿はコチラ
    </button>
  </p>
  <!-- 投稿一覧 -->
  <div class="collapse" id="collapse-titles">
    <div class="row mb-3">
      <div class="col-lg-8 offset-lg-2 text-center">
        <%= link_to t('.order_new'),
                  illustration_path,
                  class: 'btn btn-outline-dark btn-sm',
                  remote: true %>
        <%= link_to t('.order_popular'),
                  illustration_path(type: 'order_popular'),
                  class: 'btn btn-outline-dark btn-sm',
                  remote: true %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <table class="table table-hover">
          <thead>
            <tr class="table-secondary">
              <th class="col-5"><%= t('illustrations.show.posted_title') %></th>
              <th class="col-3"><%= t('illustrations.show.posted_user') %></th>
              <th class="col-2"><%= t('illustrations.show.vote_quantity') %></th>
              <th class="col-2"><%= t('illustrations.show.vote') %></th>
            </tr>
          </thead>
          <%= render 'titles/titles', { titles: @titles } %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/illustrations/show.js.erb
$("#js-table-title").replaceWith("<%= j(render 'titles/titles', { titles: @titles }) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>いらすとやタイトル選手権</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag('character_program_happy') %>

    <% if Rails.env.production? %>
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-8RY939B098"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-8RY939B098');
        gtag('config', 'UA-210348179-1');
      </script>
    <% end %>
  </head>

  <body>
    <header>
      <%= render 'shared/header' %>
      <%= render 'shared/flash_message' %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger" role="alert", id="error_messages">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'character_program_happy.png', size: '50x50'%>
    <% end %>
  </nav>
</header>

app/views/titles/_form.html.erb
<div class="row mb-3">
  <div class="col-lg-12">
    <%= form_with model: [illustration, title], local: false, id: 'new_title' do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_field :content, class: 'form-control mb-3', id: 'js-new-title-content', row: 4, placeholder: 'タイトルを入力' %>
      </div>
      <div class="form-group">
        <%= f.label :user_name %>
        <%= f.text_field :user_name, class: 'form-control mb-3', id: 'js-new-title-user_name', row: 4, placeholder: 'ニックネームを入力' %>
      </div>
      <div class="form-group">
        <%= f.hidden_field :vote_quantity, value: 0 %>
      </div>
      <%= f.submit t('defaults.post'), class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/titles/_title.html.erb
<tr id="js-title-<%= title.id %>">
  <td class="col-6">
      <%= simple_format(title.content) %>
  </td>
  <td class="col-2 small">
    <%= title.user_name %>
  </td>
  <td class="col-2">
      <%= title.vote_quantity %><%= t('defaults.vote_quantity') %>
  </td>
  <td class="col-2">
    <%= link_to votes_path(title_id: title.id),
                method: :post,
                remote: true do %>
      <%= image_tag 'text_yu.png', size: '30x30' %>
    <% end %>
  </td>
</tr>

app/views/titles/_titles.html.erb
<tbody id="js-table-title">
  <tr>
    <%= render titles %>
  </tr>
</tbody>

app/views/titles/create.js.erb
$("#error_messages").remove();
<% if @title.errors.present? %>
  $("#new_title").prepend("<%= j(render 'shared/error_messages', { object: @title }) %>");
<% else %>
  $("#js-table-title").prepend("<%= j(render 'titles/title', { title: @title }) %>");
  $("#js-new-title-user_name, #js-new-title-content").val('')
<% end %>
<%= "test" %>

app/views/votes/create.js.erb
$("#js-title-<%= @title.id %>").replaceWith("<%= j(render 'titles/title', title: @title) %>");